[package]
name = "tag-generator"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
publish = false

[dependencies]
imap-types = { version = "2.0.0-alpha.2", features = ["unvalidated"] }
rand = "0.8.5"
